@startuml
'https://plantuml.com/sequence-diagram

participant Customer
participant Merchant
participant PayPal


Customer -> Merchant : User accesses the checkout page
activate Merchant
Merchant --> Customer
deactivate Merchant

Customer -> Merchant : Customer selects PayPal Plus as payment method
activate Merchant
Merchant -> PayPal : 1. Creates a payment session with the items being sold, \n values and customer informations through REST API

activate PayPal
PayPal --> Merchant: Returns the payment session ID
deactivate PayPal

Merchant -> PayPal : 2. Renders paypal plus through JS library
activate PayPal
Merchant --> Customer :
deactivate Merchant

Customer -> PayPal : User inserts Credit Card info into the iFrame's fields
activate PayPal
PayPal --> Customer : Validates credit card BIN
deactivate PayPal
PayPal --> Merchant :
deactivate PayPal


Customer -> Merchant : User click the Place Order button
activate Merchant
Merchant -> PayPal : 3. Captures the payment through REST API
activate PayPal
PayPal --> Merchant
deactivate PayPal

Merchant --> Customer : Redirects the user to the order compleition page
deactivate Customer

@enduml
